### ISSUE TITLE
Pluto Sink missing in GNURadio

### ISSUE THREAD

**Issue by patel999jay** [LamaBleu/Pluto-DATV-test#1]
I install everything correctly but when i run dvbs_tx.grc file, GNURadio throws me error :

Pluto_Sink not found : (PS:Pluto is already connected and found.), I see the script runs without an error but not seeing anything on Rx.

This is what i have from CMD :

```
jay@jay-VirtualBox:~$ iio_info -s
Library version: 0.18 (git tag: 4e22517)
Compiled with backends: local xml ip usb serial
Available contexts:
	0: 0456:b673 (Analog Devices Inc. PlutoSDR (ADALM-PLUTO)), serial=104473dc5993001303001500ad622a4017 [usb:1.3.5]
```

**Comment by LamaBleu** [comment]
Hi,
Sorry for the delayed answer.
You have to install gr-iio (GNUradio blocks for pluto) from here : 
https://github.com/analogdevicesinc/gr-iio
Once installed it should appear in GNUradio blocks list under "Industrial IO/PlutoSDR" section.  
  
  
![image](https://user-images.githubusercontent.com/26578895/48941069-550e7880-ef1a-11e8-845d-9b060eef682a.png)


**If you installed GNUradio 3.8** you have to switch to [upgrade-3.8](https://github.com/analogdevicesinc/gr-iio/tree/upgrade-3.8) branch before installing.

After installation if IIO/plutosdr blocks don't appear on GNUradio, then you have to check files location and adapt/set your PYTHONPATH and/or LD_LIBRARY_PATH env variables, 
- Reinstalling gr-iio with correct destination directory (depends on distrib and how you installed GNUradio) is another alternative.
Keep us informed, thanks.

**Comment by patel999jay** [comment]
Thanks for getting back to me. I had installed the same and also build my GNU Radio from source files. The issue is still there(P.S. I had successfully move my lib file from usr/lib to usr/local/bin. )

`Traceback (most recent call last):
  File "C:\Users\jay_p\OneDrive\Desktop\dvbs_tx2.py", line 187, in <module>
    main()
  File "C:\Users\jay_p\OneDrive\Desktop\dvbs_tx2.py", line 181, in main
    tb = top_block_cls(uri=options.uri)
  File "C:\Users\jay_p\OneDrive\Desktop\dvbs_tx2.py", line 91, in __init__
    self.pluto_sink_0 = iio.pluto_sink('', frequency, samp_rate, 20000000, 0x8000, False, 0.0, '', True)
  File "C:\Program Files\GNURadio-3.7\lib\site-packages\gnuradio\iio\iio_pluto_sink_swig.py", line 126, in make
    return _iio_pluto_sink_swig.pluto_sink_make(*args, **kwargs)
RuntimeError: No Pluto device found`

on the same machine, and same GNU Radio i have perform all this [experiments](https://github.com/patel999jay/ADM-Pluto-File-Transfer) and it successfully detected Pluto.
![AnotherExp](https://user-images.githubusercontent.com/5512610/71362902-d4cba400-256d-11ea-9c86-e2508dd746d5.PNG)
![dvbsExample](https://user-images.githubusercontent.com/5512610/71362903-d4cba400-256d-11ea-90b3-5c9c64e86efc.PNG)

- Not sure why, this example did not found pluto.

**Comment by LamaBleu** [comment]
Hi,

So your install seems OK.
I think your problem is just the missing URI: `io.pluto_sink('', frequency, ...` usually between the quotes.  
Just try to add it on the PlutoSDR sink block ( uri=pluto.local should work)
If you prefer USB, you can also find the USB URI using iio_info.

And thank you for pointing to the link, I missed it.

**Comment by patel999jay** [comment]
Hi,

I reconfigure pluto and now it works perfectly fine. Thanks again. 

![DVB-RX](https://user-images.githubusercontent.com/5512610/71375951-43bcf300-2596-11ea-886e-c39d2ac82f5a.PNG)
![FFT PLot](https://user-images.githubusercontent.com/5512610/71375953-44558980-2596-11ea-9555-a27fa19a4e87.PNG)

Just not sure why USB webcam script didn't work. But thanks a ton.

**Comment by LamaBleu** [comment]
Thank you for reporting, closing now.

**Comment by arbimoradian** [comment]
If RuntimeError: No Pluto device found, you have to populate IIO contex URI for both PlutoSDR Source &Sink blocks with IP address: 192.168.2.1.
